volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    env_file:
      - ../.env
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - ../.env
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - ../.env