volumes:
  mariadb-v1:
    name: mariadb-v1
    driver: local
    driver_opts:
      device: /Users/juan/cursus/inception-parent/inception/v1/mariadb
      o: bind
      type: none
  wordpress-v1:
    name: wordpress-v1
    driver: local
    driver_opts:
      device: /Users/juan/cursus/inception-parent/inception/v1/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    volumes:
      - mariadb-v1:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    volumes:
      - wordpress-v1:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - wordpress-v1:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always