volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/juan/cursus/inception-parent/inception/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /Users/juan/cursus/inception-parent/inception/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always