volumes:
  wordpress-v2:
    name: wordpress-v2
    driver: local
    driver_opts:
      device: /Users/juan/cursus/inception-parent/inception/v2/wordpress
      o: bind
      type: none
  mariadb-v2:
    name: mariadb-v2
    driver: local
    driver_opts:
      device: /Users/juan/cursus/inception-parent/inception/v2/mariadb
      o: bind
      type: none

networks:
  inception:
    driver: bridge

services:
  nginx:
    build: srcs/nginx/.
    container_name: nginx-v2
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress-v2:/var/www/html
    restart: always
    networks:
      - inception
  wordpress:
    build: srcs/wordpress/.
    container_name: wordpress-v2
    volumes:
      - wordpress-v2:/var/www/html
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
  mariadb:
    build: srcs/mariadb/.
    container_name: mariadb-v2
    volumes:
      - mariadb-v2:/var/lib/mysql
    restart: always
    networks:
      - inception